http-exchange:
  base-url: http://api-gateway
  response-timeout: 10000
  headers:
    - key: X-App-Name
      values: ${spring.application.name}
  clients:
    - name: OrderApi
      base-url: http://order
      response-timeout: 1000
      headers:
        - key: X-Key
          values: [value1, value2]
    - name: UserApi
      base-url: user
      response-timeout: 2000
    - client-class: com.example.FooApi
      base-url: service-foo.namespace
