http-exchange:
  base-url: http://api-gateway
  response-timeout: 10000
  headers:
    - key: X-App-Name
      values: ${spring.application.name}
  channels:
    - base-url: http://order
      response-timeout: 1000
      headers:
        - key: X-Key
          values: [value1, value2]
      clients:
        - order-api
        - OrderDetailApi
        - com.example.api.OrderItemApi
        - com.**.*Api
        - com.example.**
    - base-url: user
      response-timeout: 2000
      classes:
        - com.example.api.UserApi
        - com.example.api.UserDetailApi
