spring:
  application:
    name: quick-start
server:
  port: 50001
http-exchange:
  channels:
    - name: localhost
      base-url: http://localhost:${server.port}
      classes:
        - com.example.api.UserApi
