server:
  ssl:
    bundle: bundle-01

spring:
  application:
    name: mtls
  config:
    import: classpath:ssl.yml
  http:
    client:
      ssl:
        bundle: bundle-01

http-exchange:
    base-packages: [ com.example.*.api ]
    channels:
        - name: user
          base-url: http://user
          clients:
            - com.example.user.api.**
        - name: order
          base-url: http://order
          ssl:
            bundle: bundle-02
          clients:
            - com.example.order.api.**
