spring:
  ssl:
    bundle:
      pem:
        bundle1:
          keystore:
            type: PEM
            certificate: classpath:bundle1/ca.crt
            private-key: classpath:bundle1/private.key
        bundle2:
          keystore:
            type: PKCS12
            certificate: classpath:bundle2/springboot.p12
