spring:
  application:
    name: native-image
http-exchange:
  request-mapping-support-enabled: true
  base-url: https://my-json-server.typicode.com
  refresh:
    enabled: true
  read-timeout: 3000
  connect-timeout: 1000
