http-exchange:
  base-packages: [com.example.api]
  base-url: http://api-gateway
  bean-to-query: false
  support-request-mapping: false
  headers:
    - key: X-App-Name
      values: ${spring.application.name}
  refresh:
    enabled: true
  channels:
    - base-url: http://order
      headers:
        - key: X-Key
          values: [value1, value2]
      clients:
        - order-api
        - OrderDetailApi
        - com.example.api.OrderItemApi
        - com.**.*Api
        - com.example.**
    - base-url: user
      classes:
        - com.example.api.UserApi
        - com.example.api.UserDetailApi
