name: Build
on:
  push:
    branches:
      - main
      - 3.*
      - 2.*
  pull_request:
    branches:
      - main
      - 3.*
      - 2.*
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'corretto'
      - uses: gradle/actions/setup-gradle@v4
      - name: Compile
        run: ./gradlew compileJava --no-daemon
  lint:
    runs-on: ubuntu-latest
    needs: [ compile ]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: 'corretto'
      - uses: gradle/actions/setup-gradle@v4
      - name: Lint
        run: ./gradlew spotlessCheck spotbugsMain --no-daemon
  test:
    runs-on: ubuntu-latest
    needs: [ compile ]
    strategy:
      matrix:
        java-version: ['17', '21', '25']
    steps:
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'corretto'
      - uses: gradle/actions/setup-gradle@v4
      - name: Test
        run: ./gradlew test --no-daemon

#  native-image-build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Check out the repo
#        uses: actions/checkout@v5
#
#      - name: Setup GraalVM
#        uses: graalvm/setup-graalvm@v1
#        with:
#          java-version: '17'
#          distribution: 'graalvm'
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#          native-image-job-reports: 'true'
#
#      - name: Setup Gradle
#        uses: gradle/actions/setup-gradle@v4
#
#      - name: Build native image
#        run: |
#          ./gradlew nativeRun
