name: Build

on:
  push:
    branches:
      - main
      - 3.3.x
      - 3.2.x
      - 3.1.x
  pull_request:
    branches:
      - main
      - 3.3.x
      - 3.2.x
      - 3.1.x

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: 'gradle'

      - name: Build
        run: ./gradlew clean build --no-daemon --stacktrace

  native-image-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Build native image
        run: |
          ./gradlew clean nativeRun --no-daemon --stacktrace
