name: Create Post on X

on:
  push:
    branches:
      - feat-x

jobs:
  create-post-on-X:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: ./tools/post-on-x/yarn.lock
      - name: Create post on X
        working-directory: ./tools/post-on-x
        env:
          X_CONSUMER_API_KEY: ${{ secrets.X_CONSUMER_API_KEY }}
          X_CONSUMER_API_SECRET_KEY: ${{ secrets.X_CONSUMER_API_SECRET_KEY }}
          X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
          X_ACCESS_TOKEN_SECRET: ${{ secrets.X_ACCESS_TOKEN_SECRET }}
        run: |
          yarn install
          yarn start
