name: Create Post on X

on:
  push:
    branches:
      - feat-x

jobs:
  create-post-on-X:
    runs-on: ubuntu-latest
    steps:
      - name: Create post on X
        working-directory: ./tools/post-on-x
        run: |
          yarn install
          yarn start
