name: Update Spring Boot Version

on:
  schedule:
    - cron: '0 4 * * *'
  push:
    branches:
      - job-upgrade-spring-boot

permissions:
  contents: write
  pull-requests: write

jobs:
  upgrade-spring-boot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upgrade Spring Boot
        run: |
          latest_version=$(curl -s 'https://repo1.maven.org/maven2/org/springframework/boot/spring-boot/maven-metadata.xml' | grep "<latest>" | sed 's/.*<latest>\(.*\)<\/latest>.*/\1/')
          echo "Latest Spring Boot version: $latest_version"
          
          current_version=$(grep 'springBootVersion' gradle.properties | cut -d'=' -f2)
          echo "Current Spring Boot version: $current_version"
          
          if [ "$current_version" == "$latest_version" ]; then
            echo "Spring Boot is up-to-date."
            exit 1
          fi
          
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          git checkout -b upgrade-spring-boot-version-$latest_version
          sed -i "s/springBootVersion=.*/springBootVersion=$latest_version/" gradle.properties
          
          git commit -am "Update Spring Boot version to $latest_version"
          git push --set-upstream origin upgrade-spring-boot-version-$latest_version
          
          echo "current_version=$current_version" >> $GITHUB_ENV
          echo "latest_version=$latest_version" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: upgrade-spring-boot-version-${{ env.latest_version }}
          title: "Update Spring Boot version to ${{ env.latest_version }}"
          body: ""
