name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Decrypt secring.gpg
        run: openssl des-cbc -d -in secring.gpg.bin -out secring.gpg -pass pass:${{ secrets.privateKeyPassword }}

      - name: Release
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish -Psigning.secretKeyRingFile=${pwd}/secring.gpg -Psigning.keyId=${{ secrets.signKeyId }} -Psigning.password=${{ secrets.signPassword }}
        env:
          RELEASE: true
          OSSRH_USER: ${{ secrets.OSSRH_USER }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
